version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  version: 2
  commit:
    jobs:
      - node/run:
          npm-run: test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - node/run
